apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-push-sa
  namespace: oci-monitoring
  labels:
    app: metrics-push-sa
    component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-push-role
  namespace: oci-monitoring
  labels:
    app: metrics-push-role
    component: monitoring
rules:
# Allow reading configmaps for pushgateway configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading pods to check daemonset status
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow reading daemonsets
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-push-rolebinding
  namespace: oci-monitoring
  labels:
    app: metrics-push-rolebinding
    component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-push-role
subjects:
- kind: ServiceAccount
  name: metrics-push-sa
  namespace: oci-monitoring
