apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-lens-config
  namespace: oci-monitoring
  labels:
    app: oci-lens-plugin
data:
  # Default configuration values
  push_gateway: "http://170.9.236.141:9091/"
  gpu_type: "amd"
  push_frequency: "10"
  job_name: "oci_lens_node_metrics"
  max_passes: "0"
  sleep_secs: "10"
  
  # GPU detection settings
  nvidia_driver_path: "/usr/local/nvidia"
  cuda_toolkit_path: "/usr/local/cuda"

  # RDMA settings
  rdma_enabled: "true"
  nvlink_enabled: "true"
  
  # Logging configuration
  log_level: "info"
  log_format: "json" 